---
# The playbook sets up a server for mongodb install

- hosts: atlanta-mdbservers
  remote_user: root
  tasks:
    - name: Upgrade all packages
      yum: name=* state=latest

    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Open port 27017
      firewalld:
        zone: public
        port: 27017/tcp
        permanent: true
        state: enabled

    - name: Install policycoreutils-python
      yum:
        name: policycoreutils-python
        state: latest

    - name: Format Drive with XFS
      filesystem:
        fstype: xfs
        dev: /dev/sdb

    - name: Create db path
      file:
        path: /data/mongodb/
        state: directory

    - name: Mount data drive
      mount:
        name: /data/mongodb
        src: /dev/sdb
        fstype: xfs
        opts: noatime
        state: present
        boot: yes

    - name: Reboot server
      shell: shutdown -r +1
      async: 0
      poll: 0

    - name: Wait for server to return
      local_action: wait_for host={{ ansible_ssh_host }} state=started
